### ISSUE TITLE
Dear, can't open the details of item, please check it~

### ISSUE THREAD

**Issue by stay4cold** [GautamGupta/toolbar-button#4]
04-15 10:54:27.380 31299-31299/com.support.android.designlibdemo E/ActivityThread: Failed to inflate
                                                                                   android.view.InflateException: Binary XML file line #155: Error inflating class am.gaut.android.toolbarbutton.ToolbarButton
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                       at com.support.android.designlibdemo.CheeseDetailActivity.onCreate(CheeseDetailActivity.java:39)
                                                                                       at android.app.Activity.performCreate(Activity.java:5242)
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5094)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                       at com.support.android.designlibdemo.CheeseDetailActivity.onCreate(CheeseDetailActivity.java:39) 
                                                                                       at android.app.Activity.performCreate(Activity.java:5242) 
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268) 
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5094) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) 
                                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                                    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/selector_toolbar_button.xml from drawable resource ID #0x7f02005a
                                                                                       at android.content.res.Resources.loadDrawable(Resources.java:2156)
                                                                                       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                                       at android.view.View.<init>(View.java:3572)
                                                                                       at android.widget.TextView.<init>(TextView.java:652)
                                                                                       at android.widget.Button.<init>(Button.java:107)
                                                                                       at am.gaut.android.toolbarbutton.ToolbarButton.<init>(ToolbarButton.java:71)
                                                                                       at am.gaut.android.toolbarbutton.ToolbarButton.<init>(ToolbarButton.java:67)
                                                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                       at com.support.android.designlibdemo.CheeseDetailActivity.onCreate(CheeseDetailActivity.java:39) 
                                                                                       at android.app.Activity.performCreate(Activity.java:5242) 
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268) 
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5094) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) 
                                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                                    Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                                       at android.content.res.TypedArray.getColor(TypedArray.java:327)
                                                                                       at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:970)
                                                                                       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
                                                                                       at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:186)
                                                                                       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
                                                                                       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                                                       at android.content.res.Resources.loadDrawable(Resources.java:2152)
                                                                                       at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                                                       at android.view.View.<init>(View.java:3572) 
                                                                                       at android.widget.TextView.<init>(TextView.java:652) 
                                                                                       at android.widget.Button.<init>(Button.java:107) 
                                                                                       at am.gaut.android.toolbarbutton.ToolbarButton.<init>(ToolbarButton.java:71) 
                                                                                       at am.gaut.android.toolbarbutton.ToolbarButton.<init>(ToolbarButton.java:67) 
                                                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                       at com.support.android.designlibdemo.CheeseDetailActivity.onCreate(CheeseDetailActivity.java:39) 
                                                                                       at android.app.Activity.performCreate(Activity.java:5242) 
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268) 
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5094) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by gautamgupta** [comment]
http://stackoverflow.com/questions/4512981/android-view-inflateexception-binary-xml-file-line-12-error-inflating-class
